// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BidMessage represents a bid request as made by a client, with its timestamp, id and the amount bid.
type BidMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`       //lamport timestamp
	BidderId      int64                  `protobuf:"varint,2,opt,name=BidderId,proto3" json:"BidderId,omitempty"`         //id of the bidder who made this bid
	Amount        int64                  `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`             //amount the bidder bids
	WasForwarded  bool                   `protobuf:"varint,4,opt,name=WasForwarded,proto3" json:"WasForwarded,omitempty"` //only the primary server will set this field to true, all others set it to false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidMessage) Reset() {
	*x = BidMessage{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidMessage) ProtoMessage() {}

func (x *BidMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidMessage.ProtoReflect.Descriptor instead.
func (*BidMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *BidMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BidMessage) GetBidderId() int64 {
	if x != nil {
		return x.BidderId
	}
	return 0
}

func (x *BidMessage) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BidMessage) GetWasForwarded() bool {
	if x != nil {
		return x.WasForwarded
	}
	return false
}

// Ack represents a response from a Node with a Timestamp of that Node as well as whether the operation succeeded failed or resulted in an exception
type Ack struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         int64                  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`                 //lamport timestamp
	Response          int32                  `protobuf:"varint,2,opt,name=Response,proto3" json:"Response,omitempty"`                   //one of three: fail, success, exception.
	CurrentLeaderPort int64                  `protobuf:"varint,3,opt,name=CurrentLeaderPort,proto3" json:"CurrentLeaderPort,omitempty"` //The server will notify the client of whom the current leader is.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Ack) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

func (x *Ack) GetCurrentLeaderPort() int64 {
	if x != nil {
		return x.CurrentLeaderPort
	}
	return 0
}

// Outcome gives the timestamp of the process which made the message, whether the auction is over and the highest (thus) far amount bid.
type Outcome struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         int64                  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`                 //lamport timestamp
	IsOver            bool                   `protobuf:"varint,2,opt,name=IsOver,proto3" json:"IsOver,omitempty"`                       //true if auction is over.
	Amount            int64                  `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`                       //highest bid thus far, or result of auction if over
	CurrentLeaderPort int64                  `protobuf:"varint,4,opt,name=CurrentLeaderPort,proto3" json:"CurrentLeaderPort,omitempty"` //The server will notify the client of whom the current leader is.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *Outcome) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Outcome) GetIsOver() bool {
	if x != nil {
		return x.IsOver
	}
	return false
}

func (x *Outcome) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Outcome) GetCurrentLeaderPort() int64 {
	if x != nil {
		return x.CurrentLeaderPort
	}
	return 0
}

// Empty is used when no argument is provided
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

type CoordinatorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	NodeId        int64                  `protobuf:"varint,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorMessage) Reset() {
	*x = CoordinatorMessage{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorMessage) ProtoMessage() {}

func (x *CoordinatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorMessage.ProtoReflect.Descriptor instead.
func (*CoordinatorMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

func (x *CoordinatorMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CoordinatorMessage) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type ElectionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	NodeId        int64                  `protobuf:"varint,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionMessage) Reset() {
	*x = ElectionMessage{}
	mi := &file_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionMessage) ProtoMessage() {}

func (x *ElectionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionMessage.ProtoReflect.Descriptor instead.
func (*ElectionMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{5}
}

func (x *ElectionMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ElectionMessage) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

// AnswerMessage is used for giving information about the process that gave the answer
type AnswerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	NodeId        int64                  `protobuf:"varint,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerMessage) Reset() {
	*x = AnswerMessage{}
	mi := &file_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerMessage) ProtoMessage() {}

func (x *AnswerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerMessage.ProtoReflect.Descriptor instead.
func (*AnswerMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{6}
}

func (x *AnswerMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AnswerMessage) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type ResultMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	CallerId      int64                  `protobuf:"varint,2,opt,name=CallerId,proto3" json:"CallerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultMessage) Reset() {
	*x = ResultMessage{}
	mi := &file_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultMessage) ProtoMessage() {}

func (x *ResultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultMessage.ProtoReflect.Descriptor instead.
func (*ResultMessage) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{7}
}

func (x *ResultMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ResultMessage) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"\x82\x01\n" +
	"\n" +
	"BidMessage\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\tTimestamp\x12\x1a\n" +
	"\bBidderId\x18\x02 \x01(\x03R\bBidderId\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\x03R\x06Amount\x12\"\n" +
	"\fWasForwarded\x18\x04 \x01(\bR\fWasForwarded\"m\n" +
	"\x03Ack\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\tTimestamp\x12\x1a\n" +
	"\bResponse\x18\x02 \x01(\x05R\bResponse\x12,\n" +
	"\x11CurrentLeaderPort\x18\x03 \x01(\x03R\x11CurrentLeaderPort\"\x85\x01\n" +
	"\aOutcome\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\tTimestamp\x12\x16\n" +
	"\x06IsOver\x18\x02 \x01(\bR\x06IsOver\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\x03R\x06Amount\x12,\n" +
	"\x11CurrentLeaderPort\x18\x04 \x01(\x03R\x11CurrentLeaderPort\"\a\n" +
	"\x05Empty\"J\n" +
	"\x12CoordinatorMessage\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\tTimestamp\x12\x16\n" +
	"\x06NodeId\x18\x02 \x01(\x03R\x06NodeId\"G\n" +
	"\x0fElectionMessage\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\tTimestamp\x12\x16\n" +
	"\x06NodeId\x18\x02 \x01(\x03R\x06NodeId\"E\n" +
	"\rAnswerMessage\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\tTimestamp\x12\x16\n" +
	"\x06NodeId\x18\x02 \x01(\x03R\x06NodeId\"I\n" +
	"\rResultMessage\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\tTimestamp\x12\x1a\n" +
	"\bCallerId\x18\x02 \x01(\x03R\bCallerId2\xf2\x01\n" +
	"\x04Node\x12\x18\n" +
	"\x03Bid\x12\v.BidMessage\x1a\x04.Ack\x12\"\n" +
	"\x06Result\x12\x0e.ResultMessage\x1a\b.Outcome\x12$\n" +
	"\bElection\x12\x10.ElectionMessage\x1a\x06.Empty\x12 \n" +
	"\x06Answer\x12\x0e.AnswerMessage\x1a\x06.Empty\x12*\n" +
	"\vCoordinator\x12\x13.CoordinatorMessage\x1a\x06.Empty\x12\x16\n" +
	"\x04Ping\x12\x06.Empty\x1a\x06.Empty\x12 \n" +
	"\x04Sync\x12\v.BidMessage\x1a\v.BidMessageB\x1aZ\x18Assignment-05/grpc/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_proto_goTypes = []any{
	(*BidMessage)(nil),         // 0: BidMessage
	(*Ack)(nil),                // 1: Ack
	(*Outcome)(nil),            // 2: Outcome
	(*Empty)(nil),              // 3: Empty
	(*CoordinatorMessage)(nil), // 4: CoordinatorMessage
	(*ElectionMessage)(nil),    // 5: ElectionMessage
	(*AnswerMessage)(nil),      // 6: AnswerMessage
	(*ResultMessage)(nil),      // 7: ResultMessage
}
var file_proto_proto_depIdxs = []int32{
	0, // 0: Node.Bid:input_type -> BidMessage
	7, // 1: Node.Result:input_type -> ResultMessage
	5, // 2: Node.Election:input_type -> ElectionMessage
	6, // 3: Node.Answer:input_type -> AnswerMessage
	4, // 4: Node.Coordinator:input_type -> CoordinatorMessage
	3, // 5: Node.Ping:input_type -> Empty
	0, // 6: Node.Sync:input_type -> BidMessage
	1, // 7: Node.Bid:output_type -> Ack
	2, // 8: Node.Result:output_type -> Outcome
	3, // 9: Node.Election:output_type -> Empty
	3, // 10: Node.Answer:output_type -> Empty
	3, // 11: Node.Coordinator:output_type -> Empty
	3, // 12: Node.Ping:output_type -> Empty
	0, // 13: Node.Sync:output_type -> BidMessage
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
